---
kind: pipeline
type: docker
name: default

steps:
  - name: version 
    image: ubuntu
    commands:
      - echo "toto"

  - name: build 
    image: plugins/docker
    commands:
      - cat /root/version
      - docker ps -a