---
kind: pipeline
type: docker
name: default

steps:
  - name: get_version
    image: ubuntu:18.04
    #volumes:
    #  - name: jitsi-version
    #    path: /root/version
    commands:
       - echo "test"
      #- apt update && apt install sudo wget gnupg
      #- wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -
      #- sudo sh -c "echo 'deb https://download.jitsi.org testing/' > /etc/apt/sources.list.d/jitsi-testing.list"
      #- apt-get -y update
      #- VERSION=$(apt-cache show jitsi-meet | grep Version | head -1) && echo ${VERSION//Version:} > /root/version
      #- cat version

  - name: build 
    image: plugins/docker
    commands:
      - cat /root/version
      - docker ps -a