---
kind: pipeline
type: docker
name: default

steps:
  - name: version 
    image: ubuntu:18.04
    volumes:
      - name: jitsi_version
        path: /root/jitsi
    commands:
      - ./get_version.sh

  - name: build 
    image: plugins/docker
    volumes:
      - name: jitsi_version
        path: /root/jitsi
    commands:
      - cat /root/jitsi/version
      - docker ps -a