---
kind: pipeline
type: docker
name: default

steps:
  - name: version 
    image: ubuntu:18.04
    volumes:
      - name: jitsi_version
        path: /root/version
    commands:
    commands:
      - echo "toto"

  - name: build 
    image: plugins/docker
    commands:
      - cat /root/version
      - docker ps -a