---
kind: pipeline
type: docker
name: default

steps:
  - name: version 
    image: ubuntu:18.04
    volumes:
      - name: jitsi
        path: /jitsi/
    commands:
      - ./get_version.sh

  - name: build 
    image: plugins/docker
    volumes:
      - name: jitsi
        path: /jitsi/
    commands:
      - cat /jitsi/version
      - docker ps -a

volumes:
- name: jitsi
  temp: {}
