image: docker:latest

services:
  - docker:dind

stages:
  - prepare
  - build

version:
  stage: prepare
  image: ubuntu:18.04
  script:
    - ./get_version.sh
  artifacts:
      paths:
        - jitsi/

build:
  stage: build
  image: docker:dind
  script:
    - cat jitsi/version
    - docker ps -a
