image: docker:latest

stages:
  - prepare
  - build

version:
  stage: prepare
  image: ubuntu:18.04
  script:
    - ./get_version.sh
  artifacts:
      paths:
        - jitsi/

checkout:
  stage: prepare
  image: alpine/git
  script:
    - mkdir jitsi && cd jitsi
    - git clone git@github.com:jitsi/docker-jitsi-meet.git
  artifacts:
      paths:
        - jitsi/

build:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  script:
    - cat jitsi/version
    - docker ps -a
    - ls jitsi
    - ls jitsi/docker-jitsi-meet
